docker/01_dockerfiles/ex02/app/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
  
  root 'welcome#index'
end

docker/01_dockerfiles/ex02/app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

docker/01_dockerfiles/ex02/app/app/models/article.rb
class Article < ApplicationRecord
	validates :title,	presence: true,
						length: { minimum: 5 }
end

docker/01_dockerfiles/ex02/app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

docker/01_dockerfiles/ex02/app/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)
	
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])
	   
		if @article.update(article_params)
		  redirect_to @article
		else
		  render 'edit'
		end
	end
	

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
	
		redirect_to articles_path
	end

	private
		def article_params
		params.require(:article).permit(:title, :text)
		end
end

docker/01_dockerfiles/ex02/app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

docker/01_dockerfiles/ex02/app/app/helpers/application_helper.rb
module ApplicationHelper
end

docker/01_dockerfiles/ex02/app/app/helpers/articles_helper.rb
module ArticlesHelper
end

docker/01_dockerfiles/ex02/app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

docker/01_dockerfiles/ex02/app/app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
	<% if @article.errors.any? %>
	  <div id="error_explanation">
		<h2>
		  <%= pluralize(@article.errors.count, "error") %> prohibited
		  this article from being saved:
		</h2>
		<ul>
		  <% @article.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		  <% end %>
		</ul>
	  </div>
	<% end %>
   
	<p>
	  <%= form.label :title %><br>
	  <%= form.text_field :title %>
	</p>
   
	<p>
	  <%= form.label :text %><br>
	  <%= form.text_area :text %>
	</p>
   
	<p>
	  <%= form.submit %>
	</p>
   
  <% end %>

docker/01_dockerfiles/ex02/app/app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

docker/01_dockerfiles/ex02/app/app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
	  <td><%= link_to 'Show', article_path(article) %></td>
	  <td><%= link_to 'Edit', edit_article_path(article) %></td>
	  <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

docker/01_dockerfiles/ex02/app/app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

docker/01_dockerfiles/ex02/app/app/views/articles/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @article.title %>
</p>

<p>
	<strong>Text:</strong>
	<%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

docker/01_dockerfiles/ex02/app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

docker/01_dockerfiles/ex02/app/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>